### PR TITLE
Travis test

### LINKED ISSUE #33: Problem with Python 3.* & Django 2.*
Hi 
Thank you for making this very useful and awesome library.
There are certain issues with this when we try to use it with python 3.* and django 2.*
We have found the fix for it, please apply these fixes so that we don't have to edit the two files everytime we install this.

    * Bug fix with the django cart package
    * Update file site-packages/cart/cart.py
    At line 2
    - *from . import models* in place of the import declaration.

and 

    *** Update file site-packages/cart/models.py
    At line 27
    replacement: cart = models.ForeignKey(Cart, verbose_name=_('cart'), on_delete=models.CASCADE)
    At line 31
    replacement: content_type = models.ForeignKey(ContentType,  on_delete=models.CASCADE)

### PR DESCRIPTION
**Pull request by MeNsaaH**
Closes #33 

- [x] Make tests run on travis and display badge
The tests is executed using tox on different versions of python and different versions of django as well

### CODE REVIEW

**Comment by MeNsaaH** [comment]
@bmentges I want to believe this is ready for the new release to pypi. I can write an automated script to deploy to pypi as well once the version is bumped to a new version

**Comment by bmentges** [comment]
Awesome. I will find time to do some cleanup and get this project back to track. Thanks @MeNsaaH

**Comment by bmentges** [comment]
And yes, please do automate the pypi release! @MeNsaaH

**Comment by MeNsaaH** [comment]
Alright on it @bmentges

**Pull request merged**
